name: CI
on: [push]

defaults:
  run: 
    shell: bash

jobs:
  # build:
  #   name: Build job
  #   runs-on: ubuntu-20.04

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby-version: [1.9.3-p551, 2.0.0-p648, 2.1.10, 2.2.10, 2.3.8, 2.4.10, 2.5.8, 2.6.6, 2.7.2, 3.0.0]

  #   container: ruby:${{ matrix.ruby-version }}

  #   steps:
  #     - uses: actions/checkout@v2      
  #     - run: gem install bundler
  #     - run: bundle install
  #     - run: rake
  
  rvm-build:
    name: RVM Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        ruby-version: [1.8.7-p374, 1.9.3-p551, 2.0.0-p648, 2.1.10, 2.2.10, 2.3.8, 2.4.10, 2.5.8, 2.6.6, 2.7.2, 3.0.]
  
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm --version
          rvm install ${{ matrix.ruby-version }}
          rvm --default use ${{ matrix.ruby-version }}
          gem install bundler --version 1.17.3
          bundle install
          rake